<?
// Wipes the stats generated by the cron. This does not wipe the log table.
// The next run of the cron file will re-populate the tables that are wiped.

$engineDir = "/home/library/phpincludes/engineAPI/engine";
include($engineDir ."/engine.php");
$engine = new EngineCMS();


$sql = sprintf("TRUNCATE TABLE %s",
	$engineDB->escape("logHits")
	);
$engineDB->sanitize = FALSE;
$sqlResult          = $engineDB->query($sql);


$sql = sprintf("TRUNCATE TABLE %s",
	$engineDB->escape("logURLs")
	);
$engineDB->sanitize = FALSE;
$sqlResult          = $engineDB->query($sql);


$sql = sprintf("TRUNCATE TABLE %s",
	$engineDB->escape("logBrowsers")
	);
$engineDB->sanitize = FALSE;
$sqlResult          = $engineDB->query($sql);


$sql = sprintf("UPDATE %s SET value='0' WHERE name='%s' LIMIT 1",
	$engineDB->escape("engineConfig"),
	$engineDB->escape("lastLogProcessed")
	);
$engineDB->sanitize = FALSE;
$sqlResult          = $engineDB->query($sql);


?>